Update model_server_playbook.yml
Add additional logs. 

Signed-off-by: Kaiyi <kaiyiliu21@gmail.com>

diff --git a/ansible/model_server_playbook.yml b/ansible/model_server_playbook.yml
--- a/ansible/model_server_playbook.yml
+++ b/ansible/model_server_playbook.yml
@@ -202,14 +202,37 @@
     # check if model server logs are operating as expected
     # for now i will just output logs    
     - name: Retrieve Model Server Logs
-      ansible.builtin.shell: docker compose -f {{ compose_path }} logs
-      register: dc_logs
+      ansible.builtin.shell: |
+        docker compose -f {{ compose_path }} logs
+        TIMEOUT=300 # Default timeout is 300 seconds (5 minutes)
+        INTERVAL=10 # Check interval is 10 seconds
+        END=$((SECONDS+TIMEOUT))
 
-    - name: Output docker compose Logs
-      ansible.builtin.debug:
-        var: dc_logs.stdout
+        while [ $SECONDS -lt $END ]; do
+          MATCH=$(docker compose logs | grep "Using Power Model")
+          if [ $? -eq 0 ]; then
+            echo "Found 'Using Power Model'"
+            echo $MATCH
+            exit 0
+          fi
+          echo "Not found yet, sleeping for $INTERVAL seconds"
+          sleep $INTERVAL
+        done
+
+        echo "Timeout reached, 'Using Power Model' not found"
+        exit 1
     
     - name: Check endpoint active
-      ansible.builtin.command: curl http://localhost:8888/metrics
-
-    # check if a well known vm metric can be reached
+      ansible.builtin.shell: |
+        for i in {1..5}; do
+          echo "Attempt $i"
+          ret=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8888/metrics --max-time 10 --connect-timeout 10 || true)
+          if [ ${ret} -eq 200 ]; then
+            exit 0
+          fi
+          sleep 5
+        done
+        echo "Kepler did not start in time"
+        exit 1
+      register: kepler_start
+      failed_when: kepler_start.rc != 0
